services:
  web-api:
    build:
      context: ./web-api
    ports:
      - "4000:3000"
    networks:
      - frontend
      - backend
    restart: unless-stopped
    depends_on:
      - app-api

  app-api:
    build:
      context: ./app-api
    ports:
      - "5000:3001"
    environment:
      PORT: 3001
      MONGO_URI: mongodb://db:27017/grocery_mart
      JWT_SECRET: mysec
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:7
    networks:
      - backend
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mondb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  frontend:
  backend:

volumes:
  mondb:


