services:
  web-api:
    image: usersystem5285/web-api:v2 
    ports:
      - "4340:4340" 
    networks:
      - frontend
      - backend
    restart: unless-stopped
    command: 

  app-api:
    image: usersystem5285/app-api:v1 
    ports:
      - "5000:5000"
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:7
    networks:
      - backend
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mondb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  frontend:
  backend:

volumes:
  mondb:

